color = {
    'face_1': 'light',
    'face_2': 'dark',
    'face_3': 'dark',
    'face_4': 'light',
    'face_5': 'dark',
    'face_6': 'light',
    'face_7': 'dark',
    'face_8': 'dark',
    'face_9': 'light',
    'face_10': 'light',
    'face_11': 'dark',
    'face_12': 'light',
    'face_13': 'light',
    'face_14': 'light',
    'face_15': 'dark',
    'face_16': 'dark',
    'face_17': 'dark',
    'face_18': 'light',
    'face_19': 'dark',
    'face_20': 'light',
}

length = {
    'face_1': 'long',
    'face_2': 'long',
    'face_3': 'short',
    'face_4': 'short',
    'face_5': 'long',
    'face_6': 'long',
    'face_7': 'long',
    'face_8': 'short',
    'face_9': 'long',
    'face_10': 'short',
    'face_11': 'short',
    'face_12': 'long',
    'face_13': 'long',
    'face_14': 'long',
    'face_15': 'short',
    'face_16': 'long',
    'face_17': 'short',
    'face_18': 'short',
    'face_19': 'short',
    'face_20': 'short',
}